
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohfgqqnxffoqukpmwqln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oZmdxcW54ZmZvcXVrcG13cWxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzEzNDEsImV4cCI6MjA2MjcwNzM0MX0.eiv6AB-5lPbFHLwEfTS6au9-HhjxeYcx-lH_mEGK9ZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
